version: '3'
services:
    pgdb:
        image: postgres:14
        restart: always
        ports:
            - '55432:5432'
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: umcmrgbot
            PGDATA: /var/lib/postgres/data/pgdata
        volumes:
            - ./pgdata:/var/lib/postgres/data/pgdata
